### ISSUE TITLE
no matching manifest for windows/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by sandersaares** [nginxinc/docker-nginx#228] opened 2018-02-14 15:45 UTC
I am unable to pull the image on Windows 10 v1709:

```
PS C:\WINDOWS\system32> docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx
latest: Pulling from library/nginx
no matching manifest for windows/amd64 in the manifest list entries
```

**Comment by tianon** [comment] 2018-02-14 20:44
This is loosely a duplicate of https://github.com/nginxinc/docker-nginx/pull/155 -- there is no Windows-based variant on `nginx`, so to use this image on Windows you'll need to use Linux containers.

**Comment by WeetA34** [comment] 2018-08-29 10:18
hi,
i have the same issue with docker ce on Windows 10 Pro 1803
I'm using linux containers.

```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false

$ docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx
no matching manifest for unknown in the manifest list entries
```

I tried the proposal of @mollyporph.
Same issue
```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true

$ docker pull --platform=linux nginx
Using default tag: latest
latest: Pulling from library/nginx
no matching manifest for linux/amd64 in the manifest list entries
```
no issue with other linux images

**Comment by WeetA34** [comment] 2018-08-29 10:58
@thresheek ok. Thx. bad timing for testing :)

**Comment by thresheek** [comment] 2019-04-23 13:09
Closing this one since there are no plans to ship windows-based nginx image.

**Closed by thresheek** 2019-04-23 13:09 UTC
