### ISSUE TITLE
Wasted my morning adding modules all wrong.

### ISSUE THREAD

**Issue by rustxj** [nginxinc/docker-nginx#530] opened 2021-04-08 11:01 UTC
**### It's better to package the docker yourself** 

debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
real 10.44
user 6.61
sys 3.74
make: *** [Makefile:162: module-brotli] Error 29
build_module.sh: ERROR: Build failed
ERROR: Service 'web' failed to build: The command '/bin/sh -c set -ex     && apt update

**Comment by thresheek** [comment] 2021-04-08 11:03
Hi @RootPeter can you show the Dockerfile you're using to build the images with a brotli module and the full commands to reproduce so I have a chance to fix it?

Thanks!

**Comment by thresheek** [comment] 2021-07-02 08:58
Closing due to feedback timeout.

**Closed by thresheek** 2021-07-02 08:58 UTC
