### ISSUE TITLE
K8S deploys arm64v8/nginx:latest without stdout stderr log output

### ISSUE THREAD

**Issue by Ardentlyer** [nginxinc/docker-nginx#931] opened 2024-09-09 18:54 UTC
### Describe the bug

K8S deploys arm64v8/nginx:latest without stdout stderr log output

### To reproduce

1.K8S cluster is an ARM environment v1.24.15
2.images  arm64v8/nginx:latest
3.Deploy nginx using Deployment     
kubectl create deployment my-arm-nginx --image=arm64v8/nginx:latest

### Expected behavior

The container nginx starts normally, but there is no log output. I hope there will be log output. 

When you start docker locally and execute docker logs, you can see the log output. But after deploying to K8S platform, you cannot see the log output. I hope you can deploy this nginx to ARM K8S cluster to verify whether there is log output. Thank you.

### Your environment

- arm64v8/nginx:latest
- Target deployment platform  Kubernetes

### Additional context

# nginx.conf
user  nginx;
worker_processes  auto;
error_log /dev/stderr warn;
pid        /var/run/nginx.pid;
events {
  worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

  access_log /dev/stdout main;
  sendfile        on;
  #tcp_nopush     on;
  
  keepalive_timeout  65;
  #gzip  on;
  #include /etc/nginx/conf.d/*.conf;
server {
  listen 80;
  server_name  localhost;

  location / {
        index index.html;
        root   /usr/share/nginx/html;
  }
  }
  }

**Comment by Ardentlyer** [comment] 2024-09-09 18:57
The nginx container deployed by K8S is in the running state, but now the container log cannot be seen

**Comment by thresheek** [comment] 2024-09-09 18:59
Hello!

Container images dont really control anything on where they're ran at.  On a start, we will log to stderr/stdout, and it's up for the container runtime (k8s) to pick it up.  If that's not happening, you need to look on how it's handled in your environment.

**Comment by Ardentlyer** [comment] 2024-09-09 19:09
Hello
    stdout and stdeer are configured in the nginx.conf file. No other processing is done on the logs in k8s. The log file content of /var/log/nginx is empty. I can't find where the logs are stored. There is no log in kubectl logs podname either.

**Comment by Ardentlyer** [comment] 2024-09-09 19:12
The configured directory does not contain any logs, so I cannot configure k8s to read the files storing logs.

**Comment by thresheek** [comment] 2024-09-09 19:17
In your configuration file you're specifying to log directly to /dev/stdout and /dev/stderr, so that's where the logs will end up at.  /var/log/nginx will be empty since it's not mentioned in the configuration file.

Anyway, with your configuration I can still see logging there (using Docker).  If logs are not there through kubectl, then you should debug k8s on why that happens, and not this image.

```
$ docker run -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf -p 8081:80 -d nginx:latest
a0a4ec8b824d2c13f30dd1db2a976fb412dea93492563412ba6513e12e88b655

$ docker logs a0a4
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

$ curl -s http://127.0.0.1:8081/ > /dev/null
$ curl -s http://127.0.0.1:8081/ > /dev/null
$ curl -s http://127.0.0.1:8081/ > /dev/null
$ curl -s http://127.0.0.1:8081/ > /dev/null

$ docker logs a0a4
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
172.17.0.1 - - [09/Sep/2024:19:14:07 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
172.17.0.1 - - [09/Sep/2024:19:14:17 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
172.17.0.1 - - [09/Sep/2024:19:14:24 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
172.17.0.1 - - [09/Sep/2024:19:14:27 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
```

**Comment by Ardentlyer** [comment] 2024-09-09 19:29
The log in nginx.conf was initially configured as
error_log /var/log/nginx/error.log warn;
access_log /var/log/nginx/access.log main;

![1](https://github.com/user-attachments/assets/aa46f724-217b-47ab-af9a-cfa944f0f99c)
![2](https://github.com/user-attachments/assets/f3c86ce9-eda7-46a2-a304-8e9977ec8475)


When I saw that K8S had no log output, I later changed it to
error_log /dev/stderr warn;
access_log /dev/stdout main;

The docker image log is normal, so how can I debug my K8S? Please give me some tips, thank you

**Comment by thresheek** [comment] 2024-09-09 19:34
I don't know, sorry.

**Comment by Ardentlyer** [comment] 2024-09-09 19:42
When deploying on the x86 platform using the nginx:latest image, the k8s nginx container log output is normal. When deploying on the ARM k8s cluster using the arm64v8/nginx:latest image, the k8s nginx container log output has no logs. You can try to deploy on the ARM platform k8s to see if the log output is normal. Thank you

**Comment by thresheek** [comment] 2024-09-09 19:44
So that means something in your ARM-based k8s is set up differently.   We don't have a test bed to reproduce this (and this is really out of scope for this project).

**Closed as completed** 2024-09-10 15:05 UTC
