### ISSUE TITLE
[WARNING]: Empty continuation lines will become errors in a future release.

### ISSUE THREAD

**Issue by khs1994** [nginxinc/docker-nginx#203] opened 2017-10-13 06:37 UTC
when fix it ?

**Comment by tianon** [comment] 2017-10-13 20:39
This is actually caused by a bug in Docker (see https://github.com/moby/moby/pull/34333), and was fixed by https://github.com/moby/moby/pull/35004 (which as can be seen at https://github.com/docker/docker-ce/commit/f6d296e26e23bd3d38b6d1e8bab8b69036055d8a is included in 17.10+).

**Closed** 2017-10-14 01:26 UTC
