### ISSUE TITLE
It seems like nginx:latest is now broken

### ISSUE THREAD

**Issue by franklouwers** [nginxinc/docker-nginx#262] opened 2018-08-29 09:16 UTC
When using nginx:latest to start a service on a Docker EE with Swarm worker nodes, the containers refuse to start. When using nginx:stable, everything works fine. 

I believe this still worked yesterday, so it must be a recent change.

**Comment by benlamptey** [comment] 2018-08-29 09:20
yeah, I'm having the same issue

`Pulling nginx (nginx:latest)...
latest: Pulling from library/nginx
ERROR: no matching manifest for unknown in the manifest list entries`

**Comment by julio641742** [comment] 2018-08-29 09:30
It is a problem with docker infrastructure. See #230 for more details

**Comment by apollotonkosmo** [comment] 2018-08-29 09:37
same here with nginx:latest . nginx:stable works though.

**Comment by kjelle** [comment] 2018-08-29 09:43
Same here

**Comment by tudor2004** [comment] 2018-08-29 09:48
same here with nginx:alpine

**Comment by Primajin** [comment] 2018-08-29 09:48
go for `nginx:1.14-alpine` until it's fixed

**Comment by ivan-kolmychek** [comment] 2018-08-29 10:00
It may be related to https://github.com/docker-library/official-images/issues/3835

**Comment by chrootlogin** [comment] 2018-08-29 10:05
Same issue here

**Comment by nbukhter** [comment] 2018-08-29 10:18
Hi, I have the same issue with nginx:alpine
`
docker pull nginx:alpine        
alpine: Pulling from library/nginx
no matching manifest for unknown in the manifest list entries
`

Is there any ETA to resolve this issue?

**Comment by maheshuluru** [comment] 2018-08-29 10:31
```
18:23:56 WARN: Failed to pull Docker image nginx:latest, retrying...
18:23:56 ERROR: Failed to pull Docker image nginx:latest: latest: Pulling from library/nginx
18:23:56 no matching manifest for linux/amd64 in the manifest list entries. Check snapshot logs for details.
18:23:56 ERROR: [Instance: xxxxxxxxxxxxxx] Command failed on instance. Return code: 1 Output: (TRUNCATED)...library/nginx
18:23:56 no matching manifest for linux/amd64 in the manifest list entries
18:23:56 Failed to pull Docker image nginx:latest: latest: Pulling from library/nginx
18:23:56 no matching manifest for linux/amd64 in the manifest list entries. Check snapshot logs for details.

**Comment by samudrala11** [comment] 2018-08-29 10:58
Same issue here, unable to pull `nginx`

**Comment by colingelling** [comment] 2018-08-29 11:00
Same issue, used nginx:stable and it is working

**Comment by KrzysztofKarol** [comment] 2018-08-29 11:49
All images `1.15.3, mainline, 1, 1.15, latest (mainline/stretch/Dockerfile)` points to 1.15.3 which is currently unavailable due to Docker infrastructure problem.
I "downgraded" `nginx:1.15.3-alpine` to `nginx:1.15.2-alpine` and it's working for me so it should work for "normal" (`nginx:1.15.2`) version

**Comment by soar** [comment] 2018-08-29 12:36
We need fix asap!

**Comment by devahmad92** [comment] 2018-08-29 13:14
same issue happen with me

**Comment by thresheek** [comment] 2018-08-29 16:14
The issue is now fixed, AFAICT.

```
thresh@coal ~ $ docker pull nginx:latest
latest: Pulling from library/nginx
be8881be8156: Already exists 
65206e5c5e2d: Pull complete 
8e029c3e2376: Pull complete 
Digest: sha256:291e15f504cdc40aeedcd29b59f0079c794e18f22cd8a6a6d66d646b36f1d51b
Status: Downloaded newer image for nginx:latest
thresh@coal ~ $ docker run -ti --rm nginx:latest nginx -V
nginx version: nginx/1.15.3

```

**Closed by thresheek** 2018-08-29 16:14 UTC
