### ISSUE TITLE
Update mainline image to 1.11.3

### ISSUE THREAD

**Issue by ziggythehamster** [nginxinc/docker-nginx#117] opened 2016-08-18 22:49 UTC
The current nginx mainline image version is 1.11.1 on DockerHub, but the latest Nginx is 1.11.3. This is probably a dupe of #88 practically, but we at least could use a refresh with the newest version of Nginx :).

**Comment by gws** [comment] 2016-08-18 23:02
It is also a dupe of https://github.com/nginxinc/docker-nginx/issues/97. The maintainer is currently on vacation.

**Comment by thresheek** [comment] 2016-08-23 12:22
Fixed by https://github.com/nginxinc/docker-nginx/commit/1f7e3c6473c2c6211c305d85cdfcfd733fe1b348

**Closed by thresheek** 2016-08-23 12:22 UTC
