### ISSUE TITLE
Nginx Alpine:3.4

### ISSUE THREAD

**Issue by wernight** [nginxinc/docker-nginx#98] opened 2016-06-09 19:41 UTC
Can you bump the version to `alpine:3.4` which is required for search domains to work on Kubernetes. The current version doesn't work on Kubernetes (unless Nginx is linked to nothing else than itself, or nothing outside `localhost`).

**Comment by thresheek** [comment] 2016-06-09 19:47
Duplicate of https://github.com/nginxinc/docker-nginx/issues/97

**Closed by thresheek** 2016-06-09 19:47 UTC
