### ISSUE TITLE
Nginx stable fails to build (1.10.3)

### ISSUE THREAD

**Issue by dgonzalez** [nginxinc/docker-nginx#160] opened 2017-04-18 15:48 UTC
With the following message:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx-module-geoip : Depends: nginx (= 1.12.0-1~jessie)
 nginx-module-image-filter : Depends: nginx (= 1.12.0-1~jessie)
 nginx-module-njs : Depends: nginx (= 1.12.0-1~jessie)
 nginx-module-perl : Depends: nginx (= 1.12.0-1~jessie)
 nginx-module-xslt : Depends: nginx (= 1.12.0-1~jessie)
E: Unable to correct problems, you have held broken packages.
```

Seems that the dependencies are broken.

**Comment by thresheek** [comment] 2017-04-18 15:53
Duplicate of #141

**Closed by thresheek** 2017-04-18 15:53 UTC
