### ISSUE TITLE
It's time to rebuild the images for CVE 2016-2107

### ISSUE THREAD

**Issue by m31271n** [nginxinc/docker-nginx#110] opened 2016-07-19 03:53 UTC
Read: https://github.com/docker-library/official-images/issues/1691. 

And nginx images is using the affected openssl (version 1.0.1k), It is time to fix it.

**Comment by thresheek** [comment] 2016-07-19 09:16
Duplicate of #88

**Closed by thresheek** 2016-07-19 09:16 UTC
