### ISSUE TITLE
Need image filter module

### ISSUE THREAD

**Issue by netroby** [nginxinc/docker-nginx#56] opened 2015-12-16 04:35 UTC
But do not want recompile it 

--with-http_image_filter_module

**Comment by thresheek** [comment] 2015-12-16 08:01
Duplicate of #2 and #14.

**Closed by thresheek** 2015-12-16 08:01 UTC

**Comment by netroby** [comment] 2015-12-16 08:51
What the hell?
You just close this ? Good idea, close issue is the good way to resolve problems. Good job

**Comment by thresheek** [comment] 2015-12-16 10:43
Well if it makes you less grumpy, I can duplicate what have been said in #14, let me quote:
"The current idea in packaging official nginx is to enable as many optional modules as long they do not require anything external, like language interpreter or a shared library. "

This will likely change when the support for dynamic modules is introduced, but so far the point still stands.
