### ISSUE TITLE
Not able to pull Nginx Docker images

### ISSUE THREAD

**Issue by Nijisha** [nginxinc/docker-nginx#264] opened 2018-08-29 11:15 UTC
Not able to pull docker images of Nginx. I have tried to pull latest and alpine tags.
it looks like it is broken. i am getting the error 'no supported platform found in manifest list'.
please look into this

**Comment by thresheek** [comment] 2018-08-29 11:25
Duplicate of #262

**Closed by thresheek** 2018-08-29 11:25 UTC

**Comment by samudrala11** [comment] 2018-08-29 16:00
Thank you team for getting to the bottom of this issue and fixing it. When can we expect this working. I am still unable to do `docker pull nginx`?
