### ISSUE TITLE
Cant pull nginx

### ISSUE THREAD

**Issue by rifqilubis** [nginxinc/docker-nginx#908] opened 2024-07-19 15:07 UTC
Im using WSL2, running ubuntu 22. I can pull other images but not nginx.

Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/library/nginx/manifests/sha256:67682bda769fae1ccf5183192b8daf37b64cae99c6c3302650f6f8bf5f0f95df": net/http: TLS handshake timeout

**Comment by oxpa** [comment] 2024-07-19 15:13
@rifqilubis this seems to be the problem with your infrastructure. The link itself works for me. And the error message suggest a networking problem.
Do you pull other images from dockerhub as well?

**Comment by rifqilubis** [comment] 2024-07-20 22:36
Yes i pull postgre images. But it worked. Only nginx that i cant pull.

Pada Jum, 19 Jul 2024, 22.14, A compound of Fe and O <
***@***.***> menulis:

**Comment by rifqilubis** [comment] 2024-07-21 03:25
It worked nows. I dont know how, it say file already exsisted and the other file can be pulled.

**Comment by thresheek** [comment] 2024-08-15 23:03
Closing since the issue is apparently solved.

**Closed by thresheek** 2024-08-15 23:03 UTC
