### ISSUE TITLE
worker_processes=auto doesn't work as expected in alpine based images

### ISSUE THREAD

**Issue by 0m1xa** [nginxinc/docker-nginx#428] opened 2020-06-18 15:48 UTC
I start image based on alpine OS
I run command inside container
`grep -c processor /proc/cpuinfo` and get result = 3
And the I run `ps aux | grep nginx | grep -cv 'daemon off' `and get result = 2
According to the [documentation ](http://nginx.org/en/docs/ngx_core_module.html#worker_processes) the number of workers must be equal the number of CPU cores

But when I run debian based image this problem doesn't appear.

Used images:
nginx:1.19-alpine
nginx:1.19

**Comment by thresheek** [comment] 2020-09-21 09:05
I'm not able to reproduce on any of hosts I use.  What are the machines you're running this on?

**Comment by 0m1xa** [comment] 2020-09-21 14:01
@thresheek 
You're right.
Today I'm not able to reproduce it too.
I think that for 3 monts code was changed and bug is not actual in latest versions.

Anyway, my host config is:
```
OS: CentOS7 (7.5.1804)
CPU: 8
```

**Comment by thresheek** [comment] 2020-10-05 12:11
Nothing has changed in nginx code for that... Closing until further reports.

**Closed by thresheek** 2020-10-05 12:11 UTC
