### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by GithubRyze** [nginxinc/docker-nginx#729] opened 2022-12-09 10:34 UTC
default.conf
```
server {
   
    listen       80;
    server_name  localhost;
    set $backend_servers 192.168.15.234:8889;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html =404;
        if ($request_uri ~* ".(html|js)$") {
                expires 1h;
                access_log off;
                add_header Pragma no-cache;
                add_header Cache-Control "private,no-cache,no-store";
                break;
        }
    }

    location /api {
        proxy_pass http://$backend_servers;
    }


    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

```

dockefile
```
FROM nginx
RUN echo Asia/Hong_Kong >/etc/timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata
COPY dist/. /usr/share/nginx/html/
COPY default.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]
```
ERROR:
```
2022/12/09 17:47:08 [error] 28#28: *56 connect() failed (113: No route to host) while connecting to upstream, client: 172.17.51.103, server: localhost, requesstream: "http://192.168.15.234:8889/api/log/apigateway_query", host: "192.168.15.234:8887", referrer: "http://192.168.15.234:8887/home/logTracer/api-gateway"
2022/12/09 17:47:20 [error] 28#28: *53 connect() failed (113: No route to host) while connecting to upstream, client: 172.17.51.103, server: localhost, reques "http://192.168.15.234:8889/api/ods-route/list", host: "192.168.15.234:8887", referrer: "http://192.168.15.234:8887/home/ods/ods-route"
172.17.51.103 - - [09/Dec/2022:17:47:20 +0800] "GET /api/ods-route/list HTTP/1.1" 502 497 "http://192.168.15.234:8887/home/ods/ods-route" "Mozilla/5.0 (Window, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
172.17.51.103 - - [09/Dec/2022:17:47:21 +0800] "GET /api/ods-route/list HTTP/1.1" 502 497 "http://192.168.15.234:8887/home/ods/ods-route" "Mozilla/5.0 (Window, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"
2022/12/09 17:47:21 [error] 28#28: *53 connect() failed (113: No route to host) while connecting to upstream, client: 172.17.51.103, server: localhost, reques "http://192.168.15.234:8889/api/ods-route/list", host: "192.168.15.234:8887", referrer: "http://192.168.15.234:8887/home/ods/ods-route"
```
Nginx container not found the backend host IP http://192.168.15.234:8889.

can anybody help me

**Comment by thresheek** [comment] 2022-12-09 16:45
Hi @GithubRyze,

That means someething is broken or firewalled on your internal network. Not an issue with nginx image.

**Comment by GithubRyze** [comment] 2022-12-12 02:28
> Hi @GithubRyze,
> 
> That means someething is broken or firewalled on your internal network. Not an issue with nginx image.

thank you reply my question。 I am checked iptables，firewalld，and ufw， there are closed or not found  in my ubuntu. 
and just this container(from nginx) cannot communication with other containers by host ip.   
```
ubuntu@techteam-dev-demo2:~$ sudo systemctl status firewalld
Unit firewalld.service could not be found.
ubuntu@techteam-dev-demo2:~$ sudo systemctl status firewalld-cmd
Unit firewalld-cmd.service could not be found.
ubuntu@techteam-dev-demo2:~$ sudo systemctl status iptables
Unit iptables.service could not be found.
ubuntu@techteam-dev-demo2:~$ sudo systemctl status ufw
● ufw.service
     Loaded: masked (Reason: Unit ufw.service is masked.)
     Active: inactive (dead) since Thu 2022-12-08 18:55:00 HKT; 3 days ago
   Main PID: 550 (code=exited, status=0/SUCCESS)

Dec 08 18:55:00 techteam-dev-demo2 systemd[1]: ufw.service: Succeeded.
Dec 08 18:55:00 techteam-dev-demo2 systemd[1]: Stopped ufw.service.
Warning: journal has been rotated since unit was started, output may be incomplete.

```
i don‘t know how to fixed!

**Comment by thresheek** [comment] 2022-12-12 17:19
Again, this seems like a networking issue in your setup. Maybe you need to open this port 8889 on the container that is supposed to run it.

**Comment by thresheek** [comment] 2023-02-15 03:05
Closing due to feedback timeout.  It's unlikely that the issue is in nginx image.

**Closed by thresheek** 2023-02-15 03:05 UTC
