### ISSUE TITLE
OpenSSL 1.1.1 LTS has been released aka TLSv1.3?

### ISSUE THREAD

**Issue by CaptainGlac1er** [nginxinc/docker-nginx#275] opened 2018-09-21 03:15 UTC
With the release of OpenSSL 1.1.1 can the next release of the nginx docker image include it to flip the switch on TLSv1.3?

**Comment by thresheek** [comment] 2018-09-22 09:28
Duplicate of #190.

**Closed by thresheek** 2018-09-22 09:28 UTC
