### ISSUE TITLE
Docs: clarify "daemon: off;"

### ISSUE THREAD

**Issue by martinlindhe** [nginxinc/docker-nginx#41] opened 2015-09-06 14:35 UTC
Hi =) Just wanted to share this as i scratched my head a while on this issue.

In the https://hub.docker.com/_/nginx/ page, the reader is encouraged to add "daemon: off;" to their nginx.conf, in this text:

> Be sure to include daemon off; in your custom configuration to ensure that Nginx stays in the foreground so that Docker can track the process properly (otherwise your container will stop immediately after starting)!

however in https://github.com/nginxinc/docker-nginx/blob/master/Dockerfile#L22 it is explicit set, which ends up in something like this

```
2015/09/06 14:13:48 [emerg] 1#1: "daemon" directive is duplicate in /etc/nginx/nginx.conf:4
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:4
```

**Comment by md5** [comment] 2015-09-06 15:07
This is a duplicate of https://github.com/docker-library/docs/issues/316

**Comment by md5** [comment] 2015-09-06 15:07
Not sure which one should be closed.

**Comment by andrefreitas** [comment] 2015-09-16 11:29
Please add in the documentation the right way to start nginx in a docker-entrypoint.sh. Lost hours figuring it out that need to write 'daemon off;' as a string param.

    exec nginx -g 'daemon off;' "$@"

**Comment by bacongobbler** [comment] 2016-10-27 20:27
@andrefreitas see https://github.com/deis/registry-proxy for a real-life example on how this image is used.

**Comment by tianon** [comment] 2017-03-17 16:36
Docs PR is merged now (https://github.com/docker-library/docs/issues/772) :+1: :heart:

**Comment by andreif** [comment] 2017-04-11 20:17
@tianon Yeah, but it's not how @andrefreitas suggested

**Closed** 2017-04-26 14:21 UTC

**Comment by gbelangervip** [comment] 2021-03-18 16:10
Wanted to add that if you are running a command like `docker run --name some-nginx -d -p 8080:80 nginx` , you need to remove the -d and that should fix the problem. If you have -d in the master process command there is no amount of 'daemon off' that will turn it off.
