### ISSUE TITLE
Alpine base cannot resolve links via DNS

### ISSUE THREAD

**Issue by rocketraman** [nginxinc/docker-nginx#78] opened 2016-04-08 23:51 UTC
Apparently there is an issue with DNS resolution in alpine. See: https://forums.docker.com/t/container-link-problem-in-docker-cloud/6445/12. This prevents nginx images from resolving linked containers via DNS, such as on Docker Cloud.

Using alpine:edge will apparently fix the issue.

**Comment by thresheek** [comment] 2016-04-11 14:02
I volunteer @tianon to decide if it's worth doing now.

**Comment by tianon** [comment] 2016-04-12 15:31
Heh :innocent:

IMO, since Alpine upstream doesn't have the fix in a release yet, we're
probably better off waiting for the next major release of Alpine since this
will be fixed for us then ("edge" is essentially Alpine's "unstable" or
"devel" suite)

**Comment by rocketraman** [comment] 2016-04-12 15:58
That makes sense. FYI, I can confirm rebuilding the container with alpine:edge as a base does indeed fix the issue, making container links work correctly on Docker Cloud. Hopefully alpine will release soon!

**Comment by Naddiseo** [comment] 2016-06-02 21:10
Is this fixed with the recently released alpine 3.4?

**Comment by Krijger** [comment] 2016-08-22 16:33
This is not fixed in 3.4, no.

**Comment by thresheek** [comment] 2016-08-23 19:13
The nginx:alpine image was rebuilt with Alpine 3.4.  Please test.

**Comment by genxstylez** [comment] 2016-08-29 08:12
not fixed

**Comment by hensansi** [comment] 2016-10-12 15:17
For me it's fixed using 1.11.4-alpine,
Nginx is able to resolve upstreams and I am able to resolve names using host.

**Comment by thresheek** [comment] 2017-03-17 14:17
Can anyone confirm if it's really fixed?  Thank you.

**Comment by andreif** [comment] 2017-04-11 19:25
`1.11.13-alpine` not fixed.

**Comment by thresheek** [comment] 2017-04-26 14:13
Please test the nginx:latest which is now based off alpine:3.5 to see if it's still an issue.

**Comment by andreif** [comment] 2017-04-26 14:48
Works fine now for `1.13.0-alpine` on macOS.

**Comment by leialexisjiang** [comment] 2017-08-12 12:36
I just tried `1.13.0-alpine` and `1.13.3-alpine`, it seems the problem is still there.

**Comment by tnguyen14** [comment] 2017-08-18 15:05
I'm seeing this problem with `1.13` `alpine` as well, not RHEL 7.3

**Comment by hirokishirai** [comment] 2017-08-29 07:51
Are there any updates?

**Comment by leialexisjiang** [comment] 2017-10-09 13:10
just tried with docker-nginx version debian which works fine, but version alpine still does not work, it seems that version alpine uses still alpine 3.5 which has DNS problem.

**Comment by andreif** [comment] 2017-10-09 13:31
```
FROM alpine:3.5
```
https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/Dockerfile#L1

**Comment by vedmant** [comment] 2018-05-12 23:58
It looks like problem is still here, so we can't use apline for swarm?

**Comment by J0WI** [comment] 2018-09-19 13:03
It works for me, but only when I add `resolver 127.0.0.11;`

**Comment by boatcoder** [comment] 2020-04-03 20:35
I'm going to say that the reason people are seeing different results is because of this tiny bit of config and the environment in which they are working....

```
  resolver 127.0.0.11 valid=30s ipv6=off;
  resolver_timeout 5s;
```

So if your environment doesn't have ipv6 available, the resolver will fail almost instantaneously and you will lose some of your hair trying to figure out why.....

**Comment by thresheek** [comment] 2021-03-02 15:50
A way to test:

```
$ docker run -n app nginx:1.19.7-alpine
ceaa16117ed4b767ce1b045effaca14e154d002443e43ae4745e51af28396d0a
$ docker run --name web --link app:app nginx:1.19.7-alpine ping -c1 app
PING app (172.17.0.2): 56 data bytes
64 bytes from 172.17.0.2: seq=0 ttl=64 time=0.150 ms

--- app ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.150/0.150/0.150 ms
```
So it works in current images. Closing it.

**Closed by thresheek** 2021-03-02 15:50 UTC
